### ISSUE TITLE
Please release/tag source

### ISSUE THREAD

**Issue by pnemade** [willthames/ansible-inventory-grapher#17]
Hi,
   I see PyPi released tarball do not have test directory but upstream have it in git. Can it be possible to release tarballs on github that will give complete tarball including test directory?

**Comment by willthames** [comment]
Hi @pnemade, I was wondering the reason for this but then I saw your username and realised it would be for the Fedora RPM update.

**Comment by willthames** [comment]
I've just tagged v2.1.0

**Comment by willthames** [comment]
Let me know if you need any other tags added

**Comment by pnemade** [comment]
Thank you for your quick response. Yes, I needed tests to execute them in rpm generation.

**Comment by willthames** [comment]
Thanks for your packaging work!
