### ISSUE TITLE
Variables don't display with ansible 2.1.1rc3

### ISSUE THREAD

**Issue by willthames** [willthames/ansible-inventory-grapher#23]
it seems that host.vars and host.get_vars don't return the results we need following the move to Ansible 2.2

variable_manager.get_vars will get host_vars but not group_vars. Need a workable solution so that the graph shows the variable source too.

**Comment by willthames** [comment]
Worse, this will hit if 2.1.1rc3 goes live. 

Tracked against ansible with ansible/ansible#16777

**Comment by DanyC97** [comment]
i guess this can be closed since the referenced ansible issue was fixed ?

**Comment by willthames** [comment]
@DanyC97 yes, this is long since fixed, quite right!
