### ISSUE TITLE
Suggestion: exclude groups

### ISSUE THREAD

**Issue by jacobweber** [willthames/ansible-inventory-grapher#34]
If you have multiple overlapping groups in your inventory, the graph output can be confusing. It might be useful if we could specify a list of groups (or group patterns) to exclude from the graph.

I'm not talking about the host patterns, which would change the hosts that appear in the graph. Just hiding some of their parent groups.

**Comment by willthames** [comment]
This seems a reasonable request but I'm unlikely to implement it myself as it's not a feature I need. I'll happily review an implementation, if you want to discuss what the implementation looks like (i.e. what the command line flags will be) beforehand, you can do that here.

**Comment by jacobweber** [comment]
I managed to do what I wanted using the template file, by adding some conditionals around which nodes get included. It might be nice if you could pass in some custom Jinja variables and filters/tests to use with the template, but I'm able to do what I need. Thanks!
