### ISSUE TITLE
Couldn't find a secret to decrypt vaulted file(s)

### ISSUE THREAD

**Issue by jacobweber** [willthames/ansible-inventory-grapher#35]
Using Ansible 2.2 and ansible-inventory-grapher 2.4.4, when I enter a vault password (using either `--ask-vault-pass` or `--vault-password-file`), I get the following error:

```
$ ansible-inventory-grapher -i /path/to/hosts --ask-vault-pass \*
Vault password: 
Couldn't find a secret to decrypt vaulted file(s)
```

**Comment by willthames** [comment]
Testing with

```
PYTHONPATH=lib:../ansible/lib bin/ansible-inventory-grapher -i test/vault/inventory --ask-vault-pass \*
```

and ansible checked out to v2.2.3.0-1 works fine for me. (Password is helloworld if you want to see if that works for you or not)

Hopefully the above command will work for you, in which case it might be worth seeing whether you can create a minimal test case that you can share with me to reproduce the error - it might be that I'm not handling certain kinds of vaulted files correctly, I'm not really sure what more to suggest.

If none of the above works, I'll look at adding some more details to the error message!

**Comment by jacobweber** [comment]
Ah, I had 2.2.0.0. Upgrading to 2.2.3.0 fixed it, so I guess it was an Ansible issue. Thanks for looking into it!
