### ISSUE TITLE
Why not pygraph?

### ISSUE THREAD

**Issue by mf69** [willthames/ansible-inventory-grapher#36]
Any plans to use pygraph or pygraphviz?

**Comment by willthames** [comment]
No, no plans. Happy enough with the current situation.

If there are compelling arguments to use them, let me know - this question seems to lack any real context as to why I might want to change ansible-inventory-grapher (or even merge other people's changes)

**Comment by mf69** [comment]
Just curious since I ran into some python doing similar things that leveraged the module. It looks like aig just uses a simple template approach to to generate the dot file.
