### ISSUE TITLE
ansible requirement should be ansible-core

### ISSUE THREAD

**Issue by nkadel** [willthames/ansible-inventory-grapher#50]
The checks for "ansible" versions should now be for "ansible-core", since ansible was factored into all the actual working code being in "ansible-core" and the "ansible" pypi.org not actually containing any of ansible, only 100 ansible collection modules and "including" ansible-core, which it does not. ansible-core is the relevent requirement from pypi.org, even though it actually installs the modules named "ansible" in the python module directories.

Yes, it's silly and confusing, but the authors show no hint of revising the packaging. Please point to "ansible-core" as the modern dependency, to avoid introducing an unwelcome and unnecessary half a Gig of local disk used for the contemporary "ansible" package.

**Comment by willthames** [comment]
Wow, this is very old, but I've finally fixed it. 

v2.6.0 restructures almost everything from a packaging perspective, and finally moves to ansible-core.

Apologies for the wait!

**Comment by sincerelysaucy** [comment]
Thank you for the cleanup!
